/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import controlador.Candidato;
import Conexion.DBConexion;
import controlador.CandidatoDAO;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileNotFoundException;
import java.sql.Blob;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class Candidatos extends javax.swing.JFrame {
    String  ruta ="";
    CandidatoDAO canHelp;
    DBConexion db;

    /**
     * Creates new form Candidatos
     */
    public Candidatos() {
        initComponents();
        
        canHelp=new CandidatoDAO();
        db=new DBConexion();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Boleta = new javax.swing.JLabel();
        Correo = new javax.swing.JLabel();
        CelularC = new javax.swing.JLabel();
        checkNO = new javax.swing.JCheckBox();
        Carrera = new javax.swing.JLabel();
        checkSI = new javax.swing.JCheckBox();
        Generacion = new javax.swing.JLabel();
        txtLugarTrabajo = new javax.swing.JTextField();
        Tema = new javax.swing.JLabel();
        txtHorario2 = new javax.swing.JTextField();
        Director = new javax.swing.JLabel();
        txtNomC = new javax.swing.JTextField();
        lblhorario = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        txtApMatC = new javax.swing.JTextField();
        txtAppC = new javax.swing.JTextField();
        txtBoleta = new javax.swing.JTextField();
        lblSI = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        lblNO = new javax.swing.JLabel();
        txtCarrera = new javax.swing.JTextField();
        txtCelular = new javax.swing.JTextField();
        txtGeneracio = new javax.swing.JTextField();
        txtTema = new javax.swing.JTextField();
        txtDirtesis = new javax.swing.JTextField();
        lblFoto = new javax.swing.JLabel();
        NombreC = new javax.swing.JLabel();
        Trabajo = new javax.swing.JLabel();
        Horario = new javax.swing.JLabel();
        ApellidoMC = new javax.swing.JLabel();
        Lugar = new javax.swing.JLabel();
        ApellidoPC = new javax.swing.JLabel();
        txtHorario1 = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logo-UACM@2x.png"))); // NOI18N
        jLabel1.setFocusTraversalPolicyProvider(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CANDIDATOS");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        Boleta.setText("Boleta");

        Correo.setText("Correo Electronico");

        CelularC.setText("Celular");

        checkNO.setText("NO");
        checkNO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkNOMouseClicked(evt);
            }
        });

        Carrera.setText("Carrera");

        checkSI.setText("SI");
        checkSI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkSIMouseClicked(evt);
            }
        });

        Generacion.setText("Generacion");

        txtLugarTrabajo.setEnabled(false);

        Tema.setText("Tema de Tesis");

        txtHorario2.setEnabled(false);

        Director.setText("Director de Tesis");

        lblhorario.setText("a");

        btnAgregar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAgregar.setText("Agregar ");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        lblSI.setVisible(false);
        lblSI.setText("SI");

        lblNO.setVisible(false);
        lblNO.setText("NO");

        txtDirtesis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDirtesisActionPerformed(evt);
            }
        });

        lblFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icono-de-archivo-de-foto_21208391.jpg"))); // NOI18N
        lblFoto.setText("      FOTO");

        NombreC.setText("Nombre");

        Trabajo.setText("Trabaja :");

        Horario.setText("Horario :");

        ApellidoMC.setText("Apellido M");

        Lugar.setText(" Lugar :");

        ApellidoPC.setText("Apellido P");

        txtHorario1.setEnabled(false);

        btnRegistrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnActualizar.setVisible(false);
        btnActualizar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ApellidoMC)
                                    .addComponent(ApellidoPC)
                                    .addComponent(NombreC))
                                .addGap(4, 4, 4)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNomC, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAppC, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtApMatC, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(CelularC)
                                    .addComponent(Correo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(133, 133, 133))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(34, 34, 34)
                                                .addComponent(Trabajo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(checkSI)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblSI)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                                                .addComponent(checkNO)
                                                .addGap(18, 18, 18)
                                                .addComponent(lblNO))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(36, 36, 36)
                                                .addComponent(Lugar)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtLugarTrabajo)))
                                        .addGap(25, 25, 25))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addComponent(Horario)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtHorario1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblhorario)
                                        .addGap(10, 10, 10)
                                        .addComponent(txtHorario2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(109, 109, 109))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnRegistrar)
                                        .addGap(28, 28, 28)
                                        .addComponent(btnCancelar)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnActualizar))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(Generacion)
                                            .addComponent(Tema)
                                            .addComponent(Director)
                                            .addComponent(Carrera)
                                            .addComponent(Boleta))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(4, 4, 4)
                                                .addComponent(txtBoleta))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtCarrera)
                                                    .addComponent(txtGeneracio)
                                                    .addComponent(txtTema)))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtDirtesis, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnAgregar)
                                            .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ApellidoPC)
                                    .addComponent(txtAppC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(NombreC)
                                .addComponent(txtNomC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ApellidoMC)
                            .addComponent(txtApMatC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Correo))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CelularC))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtBoleta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Boleta))
                                .addGap(46, 46, 46))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Carrera))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtGeneracio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Generacion)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(btnAgregar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tema)
                    .addComponent(txtTema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDirtesis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Director))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkNO)
                    .addComponent(checkSI)
                    .addComponent(Trabajo)
                    .addComponent(lblSI)
                    .addComponent(lblNO))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lugar)
                    .addComponent(txtLugarTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHorario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Horario)
                    .addComponent(txtHorario2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblhorario))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar)
                    .addComponent(btnCancelar)
                    .addComponent(btnActualizar))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(153, 0, 0));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CANDIDATOS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(262, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDirtesisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDirtesisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDirtesisActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
         JFileChooser elegirImagen = new JFileChooser();
        elegirImagen.setCurrentDirectory(new File("Imagenes/"));
        elegirImagen.setMultiSelectionEnabled(false);
        int o = elegirImagen.showOpenDialog(this);
        if (o == JFileChooser.APPROVE_OPTION) {
            ruta = elegirImagen.getSelectedFile().getAbsolutePath();
            Image preview = Toolkit.getDefaultToolkit().getImage(ruta);
            if (preview != null) {
                lblFoto.setText("");
                ImageIcon icon = new ImageIcon(preview.getScaledInstance(lblFoto.getWidth(), lblFoto.getHeight(), Image.SCALE_DEFAULT));
                lblFoto.setIcon(icon);
            }
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void checkSIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkSIMouseClicked
        // TODO add your handling code here:
        if(checkSI.isSelected())
        {   checkSI.setText("SI");
            lblSI.setVisible(true);
            checkNO.setSelected(false);
            checkNO.setText("");
            lblNO.setVisible(true);
            lblSI.setVisible(false);
            
            
            txtHorario1.setEnabled(true);
            txtHorario2.setEnabled(true);
            txtLugarTrabajo.setEnabled(true);
        }
                
    }//GEN-LAST:event_checkSIMouseClicked

    private void checkNOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkNOMouseClicked
        // TODO add your handling code here:
        if(checkNO.isSelected())
            
            checkNO.setText("NO");
            checkSI.setText("");
            lblSI.setVisible(true);
            lblNO.setVisible(false);
            
            checkSI.setSelected(false);
        txtHorario1.setEnabled(false);
            txtHorario2.setEnabled(false);
            txtLugarTrabajo.setEnabled(false);
        
    }//GEN-LAST:event_checkNOMouseClicked

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        
        if (txtBoleta.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Falto agregar Boleta", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
         if (txtNomC.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Falto agregar Nombre", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
         
          if (txtAppC.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Falto agregar Apellido Paterno", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
          
          if (txtApMatC.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Falto agregar Apellido Materno", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } 
          
         if (txtCarrera.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Falto agregar Carrera", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }  
         
          if (txtCelular.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Falto agregar Numero de Celular", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
          
           if (txtCorreo.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Falto agregar Correo Electronico", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
           
         if (txtDirtesis.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Falto agregar Director Tesis", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }  
         
         if (txtTema.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Falto agregar Tema de Tesis", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }  
         
         if ( txtLugarTrabajo.isEnabled()&& txtLugarTrabajo.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Falto agregar Lugar de Trabajo", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } 
         
         if ( txtHorario1.isEnabled()&& txtHorario1.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Falto agregar Horario de Trabajo", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } 
         
         if ( txtHorario2.isEnabled()&& txtHorario2.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Falto agregar Horario de Trabajo", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } 
         
         
         
         String imagen = ruta;
         
         String nombre =txtNomC.getText().toUpperCase();
         String aPat=txtAppC.getText().toUpperCase();
         String aMat=txtApMatC.getText().toUpperCase();
         String boleta=txtBoleta.getText().toUpperCase();
         String email=txtCorreo.getText().toUpperCase();
         String celular=txtCelular.getText().toUpperCase();
         String carrera=txtCarrera.getText().toUpperCase();
         String generacion=txtGeneracio.getText().toUpperCase();
         String dirTesis=txtDirtesis.getText().toUpperCase();
         String temTesis=txtTema.getText().toUpperCase();
         String trabaja=checkSI.getText()+checkNO.getText();
         
         String lugTrabajo=txtLugarTrabajo.getText();
        
          String horTrabajo="";
         if(checkSI.isSelected()){
             
         horTrabajo=txtHorario1.getText()+""+lblhorario.getText()+""+txtHorario2.getText();
         }
         
         Candidato candi =new Candidato(imagen, nombre, aPat, aMat, boleta, email, celular, carrera, generacion, temTesis, dirTesis, trabaja, lugTrabajo, horTrabajo);
         
         if (!ruta.equals("")) {
            
                if (canHelp.guardarImagen(candi)) {
                    JOptionPane.showMessageDialog(null, "Candidato fue Guardada Exitosamente en la Base de Datos", "Hecho", JOptionPane.INFORMATION_MESSAGE);
                    txtNomC.setText("");
                    txtGeneracio.setText("");
                    txtBoleta.setText("");
                    txtAppC.setText("");
                    txtApMatC.setText("");
                    txtCarrera.setText("");
                    txtCelular.setText("");
                    txtCorreo.setText("");
                    txtDirtesis.setText("");
                    txtTema.setText("");
                    txtHorario1.setText("");
                    txtHorario2.setText("");
                    txtLugarTrabajo.setText("");
                    checkSI.setSelected(false);
                    checkNO.setSelected(false);
                    
                ruta = "";
//                v.visualizar_tabla(tabla);
                return;
                } else {
                    JOptionPane.showMessageDialog(null, "Candidato no pudo ser Guardada en la Base de Datos", "Error", JOptionPane.ERROR_MESSAGE);
                }
             
        } else {
            JOptionPane.showMessageDialog(null, "Te falta Agregar la foto", "Error", JOptionPane.ERROR_MESSAGE);
        }
         
         


    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:}
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        
        
         
         
         try {
        Statement sent =db.getStatement();
        if(sent==null)
            return;
        
        if (txtBoleta.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Falto agregar Boleta", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
         if (txtNomC.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Falto agregar Nombre", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
         
          if (txtAppC.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Falto agregar Apellido Paterno", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
          
          if (txtApMatC.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Falto agregar Apellido Materno", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } 
          
         if (txtCarrera.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Falto agregar Carrera", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }  
         
          if (txtCelular.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Falto agregar Numero de Celular", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
          
           if (txtCorreo.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Falto agregar Correo Electronico", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
           
         if (txtDirtesis.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Falto agregar Director Tesis", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }  
         
         if (txtTema.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Falto agregar Tema de Tesis", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }  
         
         if ( txtLugarTrabajo.isEnabled()&& txtLugarTrabajo.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Falto agregar Lugar de Trabajo", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } 
         
         if ( txtHorario1.isEnabled()&& txtHorario1.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Falto agregar Horario de Trabajo", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } 
         
         if ( txtHorario2.isEnabled()&& txtHorario2.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Falto agregar Horario de Trabajo", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } 
        String sentencia="UPDATE CANDIDATOS SET NOMBRE='"+txtNomC.getText()+"',";
        sentencia+=" APELL_PATERNO='"+txtAppC.getText()+"',";
        sentencia+="APELL_MAT='"+txtApMatC.getText()+"',";
        sentencia+="EMAIL ='"+txtCorreo.getText()+"',";
        sentencia+="CELULAR='"+txtCelular.getText()+"',";
        sentencia+="CARRERA='"+txtCarrera.getText()+"',";
        sentencia+="GENERACION='"+txtGeneracio.getText()+"',";
        sentencia+="DIRECTOR_TESIS='"+txtDirtesis.getText()+"',";
        sentencia+="TEMA_TESIS='"+txtTema.getText()+"',";
        
        sentencia+="TRABAJA='"+checkSI.getText()+checkNO.getText()+"',";
        sentencia+="LUGAR_TRABAJO='"+txtLugarTrabajo.getText()+"',";
        
        sentencia+="HORARIO_TRABAJO='"+txtHorario1.getText()+""+lblhorario.getText()+""+txtHorario2.getText()+"' WHERE NUM_BOLETA='"+txtBoleta.getText()+"'";
        sent.executeUpdate(sentencia);
        JOptionPane.showMessageDialog(null, "Candidato actualizado","Transaccion realizada",JOptionPane.INFORMATION_MESSAGE);
        
    } 
    catch (SQLException ex) {
    JOptionPane.showMessageDialog(null,"No se pudo actializar el Candidato","ERROR",JOptionPane.ERROR);
    }
    
      
         
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    public void EditarPerfil(String numBoleta){
        
        Statement sent=db.getStatement();
            try {
                
                ResultSet rs = sent.executeQuery("SELECT * FROM  CANDIDATOS WHERE  NUM_BOLETA='"+numBoleta+"'");
                rs.next();
                String boleta=rs.getString("NUM_BOLETA");
                String nombre=rs.getString("NOMBRE");
                String apellPat=rs.getString("APELL_PATERNO");
                String apellMat=rs.getString("APELL_MAT");
                String email=rs.getString("EMAIL");
                String cel=rs.getString("CELULAR");
                String carrera=rs.getString("CARRERA");
                String generacion=rs.getString("GENERACION");
                String dirTesis=rs.getString("DIRECTOR_TESIS");
                String temTesis=rs.getString("TEMA_TESIS");                
                String trabaja=rs.getString("TRABAJA");
                String lugTrabajo=rs.getString("LUGAR_TRABAJO");
                String horTrabajo=rs.getString("HORARIO_TRABAJO");
                
            //Cargar imagen de la base de datos   
            Blob bytesImagen = rs.getBlob("IMAGEN");
            byte[] bytesLeidos = bytesImagen.getBytes(1, (int) bytesImagen.length());
            ImageIcon imageIcon = new ImageIcon(bytesLeidos);
            //Redimensionar la imagen
            Image imagen=imageIcon.getImage();
            Image imnuev =imagen.getScaledInstance(lblFoto.getWidth(),lblFoto.getHeight(),Image.SCALE_DEFAULT);
            //Imagen redimensionada
            imageIcon=new ImageIcon(imnuev);
            
            
                
                
                txtNomC.setText(nombre);
                txtAppC.setText(apellPat);
                txtApMatC.setText(apellMat);
                txtBoleta.setText(numBoleta);
                txtCarrera.setText(carrera);
                txtCelular.setText(cel);
                txtCorreo.setText(email);
                txtGeneracio.setText(generacion);
                txtDirtesis.setText(dirTesis);
                txtTema.setText(temTesis);
                if(checkSI.getText().equals(trabaja)){
                checkSI.setSelected(true);
                }else{
                    checkNO.setSelected(true);
                }
                txtLugarTrabajo.setText(lugTrabajo);
                txtHorario1.setText("");
                txtHorario2.setText("");
                lblFoto.setIcon(imageIcon);
                
                txtNomC.setEditable(true);
                txtAppC.setEditable(true);
                txtApMatC.setEditable(true);
                txtBoleta.setEditable(false);
                txtCarrera.setEditable(true);
                txtCelular.setEditable(true);
                txtCorreo.setEditable(true);
                txtDirtesis.setEditable(true);
                txtGeneracio.setEditable(true);
                txtHorario1.setEditable(true);
                txtLugarTrabajo.setEditable(true);
                txtTema.setEditable(true);
                txtHorario2.setVisible(true);
                lblhorario.setVisible(true);
                btnAgregar.setVisible(false);
                btnRegistrar.setVisible(false);
                btnActualizar.setVisible(true);
                
                
                
            } catch (SQLException ex) {
                Logger.getLogger(Candidatos.class.getName()).log(Level.SEVERE, null, ex);
            }
        
    
    
    }
    
    
    
    public void VerPerfil(String numBoleta)
    {
        
        Statement sent=db.getStatement();
            try {
                
                ResultSet rs = sent.executeQuery("SELECT * FROM  CANDIDATOS WHERE  NUM_BOLETA='"+numBoleta+"'");
                rs.next();
                String boleta=rs.getString("NUM_BOLETA");
                String nombre=rs.getString("NOMBRE");
                String apellPat=rs.getString("APELL_PATERNO");
                String apellMat=rs.getString("APELL_MAT");
                String email=rs.getString("EMAIL");
                String cel=rs.getString("CELULAR");
                String carrera=rs.getString("CARRERA");
                String generacion=rs.getString("GENERACION");
                String dirTesis=rs.getString("DIRECTOR_TESIS");
                String temTesis=rs.getString("TEMA_TESIS");                
                String trabaja=rs.getString("TRABAJA");
                String lugTrabajo=rs.getString("LUGAR_TRABAJO");
                String horTrabajo=rs.getString("HORARIO_TRABAJO");
                
            //Cargar imagen de la base de datos   
            Blob bytesImagen = rs.getBlob("IMAGEN");
            byte[] bytesLeidos = bytesImagen.getBytes(1, (int) bytesImagen.length());
            ImageIcon imageIcon = new ImageIcon(bytesLeidos);
            //Redimensionar la imagen
            Image imagen=imageIcon.getImage();
            Image imnuev =imagen.getScaledInstance(lblFoto.getWidth(),lblFoto.getHeight(),Image.SCALE_DEFAULT);
            //Imagen redimensionada
            imageIcon=new ImageIcon(imnuev);
            
            
                
                
                txtNomC.setText(nombre);
                txtAppC.setText(apellPat);
                txtApMatC.setText(apellMat);
                txtBoleta.setText(numBoleta);
                txtCarrera.setText(carrera);
                txtCelular.setText(cel);
                txtCorreo.setText(email);
                txtGeneracio.setText(generacion);
                txtDirtesis.setText(dirTesis);
                txtTema.setText(temTesis);
                if(checkSI.getText().equals(trabaja)){
                checkSI.setSelected(true);
                }else{
                    checkNO.setSelected(true);
                }
                txtLugarTrabajo.setText(lugTrabajo);
                txtHorario1.setText(horTrabajo);
                lblFoto.setIcon(imageIcon);
                
                txtNomC.setEditable(false);
                txtAppC.setEditable(false);
                txtApMatC.setEditable(false);
                txtBoleta.setEditable(false);
                txtCarrera.setEditable(false);
                txtCelular.setEditable(false);
                txtCorreo.setEditable(false);
                txtDirtesis.setEditable(false);
                txtGeneracio.setEditable(false);
                txtHorario1.setEditable(false);
                txtLugarTrabajo.setEditable(false);
                txtTema.setEditable(false);
                txtHorario2.setVisible(false);
                lblhorario.setVisible(false);
                btnAgregar.setEnabled(false);
                btnRegistrar.setEnabled(false);
                
                
                
            } catch (SQLException ex) {
                Logger.getLogger(Candidatos.class.getName()).log(Level.SEVERE, null, ex);
            }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Candidatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Candidatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Candidatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Candidatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Candidatos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ApellidoMC;
    private javax.swing.JLabel ApellidoPC;
    private javax.swing.JLabel Boleta;
    private javax.swing.JLabel Carrera;
    private javax.swing.JLabel CelularC;
    private javax.swing.JLabel Correo;
    private javax.swing.JLabel Director;
    private javax.swing.JLabel Generacion;
    private javax.swing.JLabel Horario;
    private javax.swing.JLabel Lugar;
    private javax.swing.JLabel NombreC;
    private javax.swing.JLabel Tema;
    private javax.swing.JLabel Trabajo;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JCheckBox checkNO;
    private javax.swing.JCheckBox checkSI;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JLabel lblNO;
    private javax.swing.JLabel lblSI;
    private javax.swing.JLabel lblhorario;
    private javax.swing.JTextField txtApMatC;
    private javax.swing.JTextField txtAppC;
    private javax.swing.JTextField txtBoleta;
    private javax.swing.JTextField txtCarrera;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDirtesis;
    private javax.swing.JTextField txtGeneracio;
    private javax.swing.JTextField txtHorario1;
    private javax.swing.JTextField txtHorario2;
    private javax.swing.JTextField txtLugarTrabajo;
    private javax.swing.JTextField txtNomC;
    private javax.swing.JTextField txtTema;
    // End of variables declaration//GEN-END:variables
}
