/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Conexion.DBConexion;
import controlador.Candidato;
import controlador.CandidatoDAO;
import controlador.CandidatosTablaM;
import controlador.GrupoHelper;
import java.awt.Image;
import java.sql.Blob;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class CandidatosTabla extends javax.swing.JFrame {
    ArrayList<Candidato> lista;
    DBConexion conexion;
    
    

    /**
     * Creates new form Aceptados
     */
    public CandidatosTabla() {
        initComponents();
      conexion =new DBConexion();
        CandidatoDAO candi=new CandidatoDAO();
        lista=candi.GetCandidatos();
        
        CandidatosTablaM modelo =new CandidatosTablaM(lista);
        tablaCandidatos.setModel(modelo);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaCandidatos = new javax.swing.JTable();
        btnEliminar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnVer = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtNumBoleta = new javax.swing.JTextField();
        btnAceptarCandidato = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        Boleta = new javax.swing.JLabel();
        Correo = new javax.swing.JLabel();
        CelularC = new javax.swing.JLabel();
        checkNO = new javax.swing.JCheckBox();
        Carrera = new javax.swing.JLabel();
        checkSI = new javax.swing.JCheckBox();
        Generacion = new javax.swing.JLabel();
        txtLugarTrabajo = new javax.swing.JTextField();
        Tema = new javax.swing.JLabel();
        txtHorario2 = new javax.swing.JTextField();
        Director = new javax.swing.JLabel();
        txtNomC = new javax.swing.JTextField();
        lblhorario = new javax.swing.JLabel();
        txtApMatC = new javax.swing.JTextField();
        txtAppC = new javax.swing.JTextField();
        txtBoleta = new javax.swing.JTextField();
        lblSI = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        lblNO = new javax.swing.JLabel();
        txtCarrera = new javax.swing.JTextField();
        txtCelular = new javax.swing.JTextField();
        txtGeneracio = new javax.swing.JTextField();
        txtTema = new javax.swing.JTextField();
        txtDirtesis = new javax.swing.JTextField();
        lblFoto = new javax.swing.JLabel();
        NombreC = new javax.swing.JLabel();
        Trabajo = new javax.swing.JLabel();
        Horario = new javax.swing.JLabel();
        ApellidoMC = new javax.swing.JLabel();
        Lugar = new javax.swing.JLabel();
        ApellidoPC = new javax.swing.JLabel();
        txtHorario1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 0, 0));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Lista De  Candidatos ");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logo-UACM@2x.png"))); // NOI18N
        jLabel2.setFocusTraversalPolicyProvider(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.getAccessibleContext().setAccessibleName("   Lista De Aceptados");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        tablaCandidatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaCandidatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaCandidatosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaCandidatos);

        btnEliminar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnEditar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnVer.setVisible(false);
        btnVer.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnVer.setText("Ver Candidato");
        btnVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerActionPerformed(evt);
            }
        });

        jLabel3.setText("Numero de Boleta");

        txtNumBoleta.setEditable(false);

        btnAceptarCandidato.setVisible(false);
        btnAceptarCandidato.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAceptarCandidato.setText("Aceptar Candidato");
        btnAceptarCandidato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarCandidatoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 486, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        Boleta.setText("Boleta");

        Correo.setText("Correo Electronico");

        CelularC.setText("Celular");

        checkNO.setText("NO");
        checkNO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkNOMouseClicked(evt);
            }
        });

        Carrera.setText("Carrera");

        checkSI.setText("SI");
        checkSI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkSIMouseClicked(evt);
            }
        });

        Generacion.setText("Generacion");

        txtLugarTrabajo.setEnabled(false);

        Tema.setText("Tema de Tesis");

        txtHorario2.setEnabled(false);

        Director.setText("Director de Tesis");

        lblhorario.setText("a");

        lblSI.setVisible(false);
        lblSI.setText("SI");

        lblNO.setVisible(false);
        lblNO.setText("NO");

        txtDirtesis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDirtesisActionPerformed(evt);
            }
        });

        lblFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icono-de-archivo-de-foto_21208391.jpg"))); // NOI18N
        lblFoto.setText("      FOTO");

        NombreC.setText("Nombre");

        Trabajo.setText("Trabaja :");

        Horario.setText("Horario :");

        ApellidoMC.setText("Apellido M");

        Lugar.setText(" Lugar :");

        ApellidoPC.setText("Apellido P");

        txtHorario1.setEnabled(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ApellidoMC)
                                    .addComponent(ApellidoPC)
                                    .addComponent(NombreC))
                                .addGap(4, 4, 4)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNomC, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAppC, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtApMatC, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(CelularC)
                                    .addComponent(Correo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(133, 133, 133))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addGap(34, 34, 34)
                                                .addComponent(Trabajo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(checkSI)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblSI)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(checkNO)
                                                .addGap(18, 18, 18)
                                                .addComponent(lblNO))
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addGap(36, 36, 36)
                                                .addComponent(Lugar)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtLugarTrabajo)))
                                        .addGap(25, 25, 25))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addComponent(Horario)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtHorario1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblhorario)
                                        .addGap(10, 10, 10)
                                        .addComponent(txtHorario2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(109, 109, 109))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Generacion)
                                    .addComponent(Tema)
                                    .addComponent(Director)
                                    .addComponent(Carrera)
                                    .addComponent(Boleta))
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(txtBoleta))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtCarrera)
                                            .addComponent(txtGeneracio)
                                            .addComponent(txtTema)))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtDirtesis, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                                .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ApellidoPC)
                            .addComponent(txtAppC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(NombreC)
                        .addComponent(txtNomC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ApellidoMC)
                            .addComponent(txtApMatC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Correo))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CelularC))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtBoleta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Boleta))
                                .addGap(46, 46, 46))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Carrera))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGeneracio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Generacion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tema)
                    .addComponent(txtTema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDirtesis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Director))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkNO)
                    .addComponent(checkSI)
                    .addComponent(Trabajo)
                    .addComponent(lblSI)
                    .addComponent(lblNO))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lugar)
                    .addComponent(txtLugarTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHorario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Horario)
                    .addComponent(txtHorario2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblhorario))
                .addGap(52, 52, 52))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNumBoleta, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnEliminar)
                                .addGap(45, 45, 45)
                                .addComponent(btnEditar)
                                .addGap(36, 36, 36)
                                .addComponent(btnVer)
                                .addGap(18, 18, 18)
                                .addComponent(btnAceptarCandidato)))))
                .addGap(10, 10, 10)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNumBoleta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminar)
                    .addComponent(btnEditar)
                    .addComponent(btnVer)
                    .addComponent(btnAceptarCandidato))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaCandidatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaCandidatosMouseClicked
        // TODO add your handling code here:
         if (evt.getClickCount()==1)
                    
        {
            int index = tablaCandidatos.getSelectedRow();
            final Candidato tall = lista.get(index);
            txtNumBoleta.setText(tall.getBoleta());
            VerPerfil(txtNumBoleta.getText());
           
        }        // TODO add your handling code here:
                               
    }//GEN-LAST:event_tablaCandidatosMouseClicked

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        
         try {
                
                Statement sent=conexion.getStatement();
                if(sent==null)
                    return;
                String sentencia="DELETE FROM CANDIDATOS  WHERE NUM_BOLETA='"+txtNumBoleta.getText()+"'";
                int estado=sent.executeUpdate(sentencia);
                if(estado==1)
                JOptionPane.showMessageDialog(null, "Candidato Eliminado","Operacion Exitosaexitosa",JOptionPane.INFORMATION_MESSAGE);
                
                } catch (SQLException ex) {
               JOptionPane.showMessageDialog(null, "Candidato  no Eliminado","Transaccion fallida",JOptionPane.ERROR_MESSAGE);
            } 
        CandidatoDAO candi=new CandidatoDAO();
        lista=candi.GetCandidatos();
        
        CandidatosTablaM modelo =new CandidatosTablaM(lista);
        tablaCandidatos.setModel(modelo);
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerActionPerformed
        // TODO add your handling code here:
        Candidatos cand =new Candidatos();
        cand.VerPerfil(txtNumBoleta.getText());
        cand.show();
    }//GEN-LAST:event_btnVerActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        
        Candidatos cand =new Candidatos();
        cand.EditarPerfil(txtNumBoleta.getText());
        cand.show();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void checkNOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkNOMouseClicked
        // TODO add your handling code here:
        if(checkNO.isSelected())

        checkNO.setText("NO");
        checkSI.setText("");
        lblSI.setVisible(true);
        lblNO.setVisible(false);

        checkSI.setSelected(false);
        txtHorario1.setEnabled(false);
        txtHorario2.setEnabled(false);
        txtLugarTrabajo.setEnabled(false);

    }//GEN-LAST:event_checkNOMouseClicked

    private void checkSIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkSIMouseClicked
        // TODO add your handling code here:
        if(checkSI.isSelected())
        {   checkSI.setText("SI");
            lblSI.setVisible(true);
            checkNO.setSelected(false);
            checkNO.setText("");
            lblNO.setVisible(true);
            lblSI.setVisible(false);

            txtHorario1.setEnabled(true);
            txtHorario2.setEnabled(true);
            txtLugarTrabajo.setEnabled(true);
        }

    }//GEN-LAST:event_checkSIMouseClicked

    private void txtDirtesisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDirtesisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDirtesisActionPerformed

    private void btnAceptarCandidatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarCandidatoActionPerformed
        // TODO add your handling code here:
        
        //falta revisar este metodo crea diferentes grupos al agregar cada candidato
       GrupoHelper gHelp=new GrupoHelper();
       
       int aux=gHelp.numeroGrupos();
       
       if(aux<25){
       gHelp.InsertarGrupo(aux);
       gHelp.InsertarMienbroAlGrupo(txtNumBoleta.getText(),aux);
       
       }else {
           gHelp.InsertarGrupo(aux);
       gHelp.InsertarMienbroAlGrupo(txtNumBoleta.getText(),aux+1);
       }
           
        
    }//GEN-LAST:event_btnAceptarCandidatoActionPerformed

    
    
    
    
     public void VerPerfil(String numBoleta)
    {
        
        Statement sent=conexion.getStatement();
            try {
                
                ResultSet rs = sent.executeQuery("SELECT * FROM  CANDIDATOS WHERE  NUM_BOLETA='"+numBoleta+"'");
                rs.next();
                String boleta=rs.getString("NUM_BOLETA");
                String nombre=rs.getString("NOMBRE");
                String apellPat=rs.getString("APELL_PATERNO");
                String apellMat=rs.getString("APELL_MAT");
                String email=rs.getString("EMAIL");
                String cel=rs.getString("CELULAR");
                String carrera=rs.getString("CARRERA");
                String generacion=rs.getString("GENERACION");
                String dirTesis=rs.getString("DIRECTOR_TESIS");
                String temTesis=rs.getString("TEMA_TESIS");                
                String trabaja=rs.getString("TRABAJA");
                String lugTrabajo=rs.getString("LUGAR_TRABAJO");
                String horTrabajo=rs.getString("HORARIO_TRABAJO");
                
            //Cargar imagen de la base de datos   
            Blob bytesImagen = rs.getBlob("IMAGEN");
            byte[] bytesLeidos = bytesImagen.getBytes(1, (int) bytesImagen.length());
            ImageIcon imageIcon = new ImageIcon(bytesLeidos);
            //Redimensionar la imagen
            Image imagen=imageIcon.getImage();
            Image imnuev =imagen.getScaledInstance(lblFoto.getWidth(),lblFoto.getHeight(),Image.SCALE_DEFAULT);
            //Imagen redimensionada
            imageIcon=new ImageIcon(imnuev);
            
            
                
                
                txtNomC.setText(nombre);
                txtAppC.setText(apellPat);
                txtApMatC.setText(apellMat);
                txtBoleta.setText(numBoleta);
                txtCarrera.setText(carrera);
                txtCelular.setText(cel);
                txtCorreo.setText(email);
                txtGeneracio.setText(generacion);
                txtDirtesis.setText(dirTesis);
                txtTema.setText(temTesis);
                if(checkSI.getText().equals(trabaja)){
                checkSI.setSelected(true);
                }else{
                    checkNO.setSelected(true);
                }
                txtLugarTrabajo.setText(lugTrabajo);
                txtHorario1.setText(horTrabajo);
                lblFoto.setIcon(imageIcon);
                
                txtNomC.setEditable(false);
                txtAppC.setEditable(false);
                txtApMatC.setEditable(false);
                txtBoleta.setEditable(false);
                txtCarrera.setEditable(false);
                txtCelular.setEditable(false);
                txtCorreo.setEditable(false);
                txtDirtesis.setEditable(false);
                txtGeneracio.setEditable(false);
                txtHorario1.setEditable(false);
                txtLugarTrabajo.setEditable(false);
                txtTema.setEditable(false);
                txtHorario2.setVisible(false);
                lblhorario.setVisible(false);
               
                
                
                
            } catch (SQLException ex) {
                Logger.getLogger(Candidatos.class.getName()).log(Level.SEVERE, null, ex);
            }
    }
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CandidatosTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CandidatosTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CandidatosTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CandidatosTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CandidatosTabla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ApellidoMC;
    private javax.swing.JLabel ApellidoPC;
    private javax.swing.JLabel Boleta;
    private javax.swing.JLabel Carrera;
    private javax.swing.JLabel CelularC;
    private javax.swing.JLabel Correo;
    private javax.swing.JLabel Director;
    private javax.swing.JLabel Generacion;
    private javax.swing.JLabel Horario;
    private javax.swing.JLabel Lugar;
    private javax.swing.JLabel NombreC;
    private javax.swing.JLabel Tema;
    private javax.swing.JLabel Trabajo;
    private javax.swing.JButton btnAceptarCandidato;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnVer;
    private javax.swing.JCheckBox checkNO;
    private javax.swing.JCheckBox checkSI;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JLabel lblNO;
    private javax.swing.JLabel lblSI;
    private javax.swing.JLabel lblhorario;
    private javax.swing.JTable tablaCandidatos;
    private javax.swing.JTextField txtApMatC;
    private javax.swing.JTextField txtAppC;
    private javax.swing.JTextField txtBoleta;
    private javax.swing.JTextField txtCarrera;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDirtesis;
    private javax.swing.JTextField txtGeneracio;
    private javax.swing.JTextField txtHorario1;
    private javax.swing.JTextField txtHorario2;
    private javax.swing.JTextField txtLugarTrabajo;
    private javax.swing.JTextField txtNomC;
    private javax.swing.JTextField txtNumBoleta;
    private javax.swing.JTextField txtTema;
    // End of variables declaration//GEN-END:variables
}
